import { test, expect } from '@playwright/test';

test('concept explorer saves layouts, links cards and spaces, and exports a portable canvas', async ({ page, request }) => {
  const a = await (await request.post('/api/topics', { data: { title: 'Cardiac physiology' } })).json();
  const b = await (await request.post('/api/topics', { data: { title: 'Ultrasound principles' } })).json();
  const graph = { nodes: [{ id: 'pressure', label: 'Pressure gradient', description: 'A difference in pressure between two locations.' }, { id: 'flow', label: 'Blood flow', description: 'Movement through the circulation.' }, { id: 'resistance', label: 'Vascular resistance', description: 'Opposition to flow.' }, { id: 'output', label: 'Cardiac output', description: 'The volume pumped per minute.' }], edges: [{ from: 'pressure', to: 'flow', label: 'drives', source: 'Physiology notes' }, { from: 'resistance', to: 'flow', label: 'limits', source: 'Physiology notes' }, { from: 'flow', to: 'output', label: 'contributes to', source: 'Physiology notes' }] };
  await request.put(`/api/topics/${a.id}/graph`, { data: graph });
  await request.put(`/api/topics/${b.id}/graph`, { data: { nodes: [{ id: 'doppler', label: 'Doppler', description: 'Uses frequency shifts to assess motion.' }], edges: [] } });
  const withCard = await (await request.post(`/api/topics/${a.id}/cards`, { data: { front: 'What drives flow?', back: 'A pressure gradient.' } })).json();
  await page.goto('/'); await page.getByRole('navigation').getByRole('button', { name: 'Cardiac physiology', exact: true }).click();
  await page.getByRole('button', { name: 'Concept map', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Pressure gradient', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Pressure gradient', exact: true }).click();
  await expect(page.getByRole('complementary', { name: 'Concept details' }).getByText('A difference in pressure between two locations.')).toBeVisible();
  await page.getByLabel('Link a flashcard', { exact: true }).selectOption(withCard.cards[0].id);
  await expect(page.getByRole('button', { name: /What drives flow/ })).toBeVisible();
  await page.getByRole('button', { name: 'Unlink flashcard', exact: true }).click();
  await expect(page.getByRole('button', { name: /What drives flow/ })).toHaveCount(0);
  expect((await (await request.get('/api/state')).json()).topics.find(t => t.id === a.id).cards).toHaveLength(1);
  await page.getByLabel('Link a flashcard', { exact: true }).selectOption(withCard.cards[0].id);
  await page.getByRole('button', { name: 'Arrange', exact: true }).click();
  await expect.poll(async () => (await (await request.get('/api/state')).json()).topics.find(t => t.id === a.id).graph.nodes.every(n => Number.isFinite(n.position?.x))).toBeTruthy();
  const before = (await (await request.get('/api/state')).json()).topics.find(t => t.id === a.id).graph.nodes[0].position;
  await page.getByLabel('Concept in another space').selectOption(`${b.id}::doppler`);
  await page.getByLabel('Cross-space relationship').fill('assessed using');
  await page.getByLabel('Cross-space source').fill('Teaching notes, chapter 2');
  await page.getByRole('button', { name: 'Connect concepts', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'The bigger picture' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Doppler', exact: true })).toBeVisible();
  await page.locator('.react-flow__edge-textwrapper').filter({ hasText: 'assessed using' }).click();
  await expect(page.getByRole('complementary', { name: 'Concept details' }).getByText('Teaching notes, chapter 2', { exact: true })).toBeVisible();
  await page.getByLabel('Edit relationship', { exact: true }).fill('can be assessed using');
  await page.getByLabel('Edit relationship source').fill('Teaching notes, chapter 3');
  await page.getByRole('button', { name: 'Save relationship', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'can be assessed using', exact: true })).toBeVisible();
  await expect.poll(async () => (await (await request.get('/api/state')).json()).conceptLinks.find(l => l.fromTopic === a.id)?.source).toBe('Teaching notes, chapter 3');
  await page.getByRole('button', { name: 'Close concept details' }).click();
  const downloadPromise = page.waitForEvent('download'); await page.getByRole('button', { name: 'Export Obsidian canvas' }).click();
  const download = await downloadPromise; const stream = await download.createReadStream(); const parts = []; for await (const part of stream) parts.push(part); const canvas = JSON.parse(Buffer.concat(parts).toString());
  expect(canvas.edges.some(e => e.label === 'can be assessed using\nSource: Teaching notes, chapter 3')).toBeTruthy();
  await page.getByLabel('Find a concept', { exact: true }).fill('frequency');
  await expect(page.locator('.map-search-results')).toContainText('Doppler');
  await page.getByRole('button', { name: 'Clear concept search' }).click();
  await page.screenshot({ path: '/tmp/lumen-atlas-desktop.png', fullPage: true });
  await page.getByRole('button', { name: 'This space', exact: true }).click();
  await page.reload(); await page.getByRole('button', { name: 'Concept map', exact: true }).click();
  expect((await (await request.get('/api/state')).json()).topics.find(t => t.id === a.id).graph.nodes[0].position).toEqual(before);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'Pressure gradient', exact: true }).click();
  await expect(page.getByRole('complementary', { name: 'Concept details' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.screenshot({ path: '/tmp/lumen-map-mobile.png', fullPage: true });
});
