import { test, expect } from '@playwright/test';
test('study workspace persists sources, editable graph, cards, review and export', async ({ page }) => {
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Follow your curiosity. Make it stay.' })).toBeVisible();
  await page.getByRole('button', { name: 'New topic' }).click();
  await page.getByLabel('Topic name').fill('Retrieval practice');
  await page.getByRole('button', { name: 'Let’s begin' }).click();
  await expect(page.getByRole('heading', { name: 'Retrieval practice' })).toBeVisible();
  await page.getByRole('button', { name: 'I have material to work with' }).click();
  await page.getByLabel('Title', { exact: true }).fill('Study notes');
  await page.getByLabel('Notes or source text').fill('Retrieval practice means recalling knowledge from memory. Feedback helps correct errors.');
  await page.getByRole('button', { name: 'Add to sources' }).click();
  await page.getByRole('button', { name: 'Sources', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Study notes' })).toBeVisible();
  await page.getByRole('button', { name: 'Add material', exact: true }).click();
  await page.locator('input[type=file]').setInputFiles({ name: 'chapter.md', mimeType: 'text/markdown', buffer: Buffer.from('# Spacing\nStudy at separated intervals.') });
  await expect(page.getByRole('heading', { name: 'chapter.md' })).toBeVisible();
  await page.getByRole('button', { name: 'Concept map', exact: true }).click();
  await page.getByRole('button', { name: 'Edit map' }).click();
  await page.getByRole('button', { name: 'Add concept' }).click();
  await page.getByLabel('Concept 1 name').fill('Retrieval');
  await page.getByLabel('Concept 1 description').fill('Recall from memory.');
  await page.getByRole('button', { name: 'Add concept' }).click();
  await page.getByLabel('Concept 2 name').fill('Feedback');
  await page.getByRole('button', { name: 'Add connection' }).click();
  await page.getByLabel('Connection 1 relationship').fill('benefits from');
  await page.getByLabel('Connection 1 source').fill('Study notes');
  await page.getByRole('button', { name: 'Save map' }).click();
  await page.getByRole('button', { name: 'Retrieval', exact: true }).click();
  await expect(page.getByText('Recall from memory.', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Flashcards', exact: true }).click();
  await page.getByRole('button', { name: 'Add card' }).click();
  await page.getByLabel('Question').fill('What is retrieval practice?');
  await page.getByLabel('Answer').fill('Recalling information from memory.');
  await page.getByLabel('Source', { exact: true }).fill('Study notes');
  await page.getByRole('button', { name: 'Save flashcard' }).click();
  await expect(page.getByRole('heading', { name: 'What is retrieval practice?' })).toBeVisible();
  const downloadPromise = page.waitForEvent('download'); await page.getByRole('link', { name: 'Anki' }).click();
  const download = await downloadPromise; expect(download.suggestedFilename()).toBe('lumen-anki.tsv');
  await page.getByRole('button', { name: 'Review 1' }).click();
  await page.getByRole('button', { name: 'Reveal answer' }).click();
  await page.getByRole('button', { name: 'Good 10 min' }).click();
  await expect(page.getByRole('heading', { name: 'A little stronger than before.' })).toBeVisible();
  await page.getByRole('button', { name: 'Back to your learning space' }).click();
  await page.reload();
  await page.getByRole('button', { name: 'Flashcards', exact: true }).click();
  await expect(page.getByText('1 reviews', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Review', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Progress', exact: true }).click();
  await expect(page.getByText('Connecting the dots', { exact: true })).toBeVisible();
  await page.screenshot({ path: '/tmp/lumen-progress.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole('heading', { name: 'Small steps add up.' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.screenshot({ path: '/tmp/lumen-mobile.png', fullPage: true });
  expect(errors).toEqual([]);
});
test('server rejects foreign origins and unsafe links', async ({ request }) => {
  expect((await request.post('/api/topics', { headers: { Origin: 'https://example.com' }, data: { title: 'Blocked' } })).status()).toBe(403);
  const t = await (await request.post('/api/topics', { data: { title: 'Validation' } })).json();
  expect((await request.post(`/api/topics/${t.id}/sources`, { data: { title: 'Unsafe', url: 'javascript:alert(1)' } })).status()).toBe(400);
  expect((await request.put(`/api/topics/${t.id}/graph`, { data: { nodes: [], edges: [{ from: 'a', to: 'b' }] } })).status()).toBe(400);
});
test('text PDF upload extracts source material', async ({ page, request }) => {
  await page.setContent('<h1>Learning notes</h1><p>Retrieval practice means recalling information from memory. Feedback helps identify errors.</p>');
  const pdf = await page.pdf();
  const t = await (await request.post('/api/topics', { data: { title: 'PDF import check' } })).json();
  const upload = await request.post(`/api/topics/${t.id}/upload`, { multipart: { file: { name: 'learning.pdf', mimeType: 'application/pdf', buffer: pdf } } });
  expect(upload.status()).toBe(200);
  const result = await upload.json();
  expect(result.sources[0].content).toContain('Retrieval practice means recalling information from memory.');
});
test('invalid card edits do not corrupt saved card content', async ({ request }) => {
  const t = await (await request.post('/api/topics', { data: { title: 'Card validation' } })).json();
  const withCard = await (await request.post(`/api/topics/${t.id}/cards`, { data: { front: 'Question?', back: 'Answer.' } })).json();
  const result = await request.patch(`/api/topics/${t.id}/cards/${withCard.cards[0].id}`, { data: { front: '' } });
  expect(result.status()).toBe(400);
  const state = await (await request.get('/api/state')).json();
  expect(state.topics.find(x => x.id === t.id).cards[0].front).toBe('Question?');
});
test('FSRS previews commit exact intervals, record full history, and reject duplicate reviews', async ({ request }) => {
  const t = await (await request.post('/api/topics', { data: { title: 'FSRS scheduling' } })).json();
  const topic = await (await request.post(`/api/topics/${t.id}/cards`, { data: { front: 'Recall?', back: 'Answer' } })).json();
  const c = topic.cards[0]; const url = `/api/topics/${t.id}/cards/${c.id}`;
  const preview = await (await request.get(`${url}/preview`)).json();
  expect(preview.options.again.label).toBe('1 min'); expect(preview.options.good.label).toBe('10 min');
  expect((await request.post(`${url}/review`, { data: { grade: 'invalid', token: preview.token } })).status()).toBe(400);
  const answer = await request.post(`${url}/review`, { data: { grade: 'good', token: preview.token } });
  expect(answer.status()).toBe(200); const saved = (await answer.json()).cards[0];
  expect(saved.due).toBe(preview.options.good.due); expect(saved.fsrs.stability).toBeGreaterThan(0);
  expect(saved.fsrs.state).toBe(1); expect(saved.fsrs.reps).toBe(1);
  expect((await request.post(`${url}/review`, { data: { grade: 'good', token: preview.token } })).status()).toBe(409);
  expect((await request.get(`${url}/preview`)).status()).toBe(409);
  const state = await (await request.get('/api/state')).json();
  const logs = state.reviews.filter(r => r.cardId === c.id); expect(logs).toHaveLength(1);
  expect(logs[0].log.rating).toBe(3); expect(logs[0].before.state).toBe(0); expect(logs[0].after.state).toBe(1);
});
test('learning cards return to an open review session when due', async ({ page, request }) => {
  const t = await (await request.post('/api/topics', { data: { title: 'Learning queue' } })).json();
  await request.post(`/api/topics/${t.id}/cards`, { data: { front: 'What returns?', back: 'A learning card.' } });
  await page.goto('/'); await page.getByRole('button', { name: 'Learning queue' }).click();
  await page.getByRole('button', { name: 'Flashcards' }).click();
  await page.getByRole('button', { name: 'Review 1' }).click();
  await page.getByRole('button', { name: 'Reveal answer' }).click();
  await page.getByRole('button', { name: 'Again 1 min' }).click();
  await expect(page.getByText(/A learning card returns in/)).toBeVisible();
  await page.clock.install(); await page.clock.fastForward(61000);
  await expect(page.getByRole('dialog').getByRole('heading', { name: 'What returns?' })).toBeVisible();
});
