import React, { useEffect, useMemo, useState } from 'react';
import { ReactFlow, Background, Controls, MiniMap, Handle, Position, MarkerType, useNodesState } from '@xyflow/react';
import { ArrowUpRight, BookOpen, Check, Download, Layers, Link2, LocateFixed, Maximize2, Network, Pencil, Search, Sparkles, X } from 'lucide-react';
import '@xyflow/react/dist/style.css';
import { buildGraph, canvasExport, layoutGraph, neighborhood, nodeKey } from './graph-model.js';
import { dueLabel } from './study.js';

function ConceptNode({ data, selected }) {
  return <div className={'concept-node-card ' + (selected ? 'is-selected' : '')} role="button" aria-label={data.label} tabIndex={0} onKeyDown={e => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); e.currentTarget.click(); } }}>
    <Handle type="target" position={Position.Left} isConnectable={false}/>
    <div className="concept-node-topic"><span/>{data.topicTitle}</div><strong>{data.label}</strong>
    <p>{data.description || 'Add a description to develop this idea.'}</p>
    <div className="concept-node-foot"><BookOpen size={11}/>{data.cards.length ? `${data.cards.filter(c => c.reviews > 0).length}/${data.cards.length} cards practised` : 'Explore concept'}</div>
    <Handle type="source" position={Position.Right} isConnectable={false}/>
  </div>;
}
const nodeTypes = { concept: ConceptNode };
const safeURL = text => /^https?:\/\//i.test(text || '');

function CrossLinkEditor({ edge, save, busy }) {
  const [label, setLabel] = useState(edge.label), [source, setSource] = useState(edge.data.source || '');
  return <form className="inspector-section" onSubmit={e => { e.preventDefault(); save({ label, source }); }}><h4>Edit this relationship</h4><label className="inspector-label">Relationship<input required maxLength={120} aria-label="Edit relationship" value={label} onChange={e => setLabel(e.target.value)}/></label><label className="inspector-label">Source title or URL<input maxLength={2000} aria-label="Edit relationship source" value={source} onChange={e => setSource(e.target.value)}/></label><button className="button secondary" disabled={busy || !label.trim()} type="submit"><Check size={14}/>Save relationship</button></form>;
}

export function ConceptMap({ topic, topics, links = [], onEdit, onAsk, onOpenTopic, onLayout, onLink, onUnlink, onUpdateLink, onCards, onAttachCard }) {
  const [atlas, setAtlas] = useState(false), [selected, setSelected] = useState(null), [selectedEdge, setSelectedEdge] = useState(null), [query, setQuery] = useState(''), [focus, setFocus] = useState(false), [expanded, setExpanded] = useState(false), [instance, setInstance] = useState(null), [error, setError] = useState(''), [saving, setSaving] = useState(false), [target, setTarget] = useState(''), [relationship, setRelationship] = useState('relates to'), [relationshipSource, setRelationshipSource] = useState('');
  const signature = JSON.stringify([topics.map(t => [t.id, t.title, t.graph, t.cards.map(c => [c.id, c.reviews, c.suspended, c.front, c.due, c.anki?.dueNow])]), links, topic.id, atlas]);
  const model = useMemo(() => buildGraph(topics, links, topic.id, atlas), [signature]);
  const [nodes, setNodes, onNodesChange] = useNodesState([]);
  useEffect(() => { setNodes(layoutGraph(model.nodes, model.edges, !atlas)); }, [model]);
  useEffect(() => { setSelected(null); setSelectedEdge(null); setFocus(false); }, [atlas, topic.id]);
  useEffect(() => { if (instance && nodes.length) { const timer = setTimeout(() => instance.fitView({ padding: .2, duration: 350, maxZoom: 1 }), 80); return () => clearTimeout(timer); } }, [instance, atlas, topic.id, nodes.length, expanded]);
  const node = model.nodes.find(n => n.id === selected), edge = model.edges.find(e => e.id === selectedEdge);
  const neighborhoodIds = neighborhood(model.nodes, model.edges, focus ? selected : null);
  const matches = model.nodes.filter(n => `${n.data.label} ${n.data.description} ${n.data.topicTitle}`.toLowerCase().includes(query.toLowerCase()));
  const matchIds = new Set(matches.map(n => n.id));
  const displayNodes = nodes.map(n => ({ ...n, selected: n.id === selected, hidden: !neighborhoodIds.has(n.id), style: { opacity: query && !matchIds.has(n.id) ? .22 : 1 }, ariaLabel: n.data.label }));
  const displayEdges = model.edges.map(e => ({ ...e, type: 'smoothstep', hidden: !neighborhoodIds.has(e.source) || !neighborhoodIds.has(e.target), selected: e.id === selectedEdge,
    markerEnd: { type: MarkerType.ArrowClosed, color: e.data.crossTopic ? '#a58250' : '#809889' },
    style: { stroke: e.data.crossTopic ? '#a58250' : '#91a597', strokeWidth: selected && (e.source === selected || e.target === selected) ? 2.5 : 1.4, strokeDasharray: e.data.crossTopic ? '6 4' : undefined },
    labelStyle: { fill: '#4c6557', fontSize: 11 }, labelBgStyle: { fill: '#f8f9f5', fillOpacity: .96 }, labelBgPadding: [8, 5], labelBgBorderRadius: 5,
  }));
  async function run(fn) { setError(''); setSaving(true); try { await fn(); } catch (e) { setError(e.message); } finally { setSaving(false); } }
  function selectNode(id) { setSelected(id); setSelectedEdge(null); const n = nodes.find(n => n.id === id); if (n && instance) instance.setCenter(n.position.x + 118, n.position.y + 58, { zoom: 1, duration: 400 }); }
  const allOtherConcepts = topics.filter(t => t.id !== node?.data.topicId).flatMap(t => t.graph.nodes.map(n => ({ ...n, topic: t, value: nodeKey(t.id, n.id) })));
  const connectedEdges = node ? model.edges.filter(e => e.source === node.id || e.target === node.id) : [];
  function download() { const blob = new Blob([JSON.stringify(canvasExport(nodes, model.edges), null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = (atlas ? 'Lumen atlas' : topic.title).replace(/[^\p{L}\p{N} _-]/gu, '') + '.canvas'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
  return <section className={'concept-map-page ' + (expanded ? 'expanded-map' : '')} aria-label="Concept explorer">
    <div className="map-heading"><div><div className="eyebrow"><Network size={14}/> YOUR KNOWLEDGE, CONNECTED</div><h2>{atlas ? 'The bigger picture' : 'See how it fits together'}</h2><p>{atlas ? 'Explore your learning spaces together. Dashed lines are connections you have made.' : 'Follow a connection. Discover the relationship. Make the idea your own.'}</p></div><div className="actions"><button className="button secondary" onClick={onEdit}><Pencil size={15}/>Edit map</button><button className="map-icon-button" aria-label={expanded ? 'Exit expanded map' : 'Expand map'} onClick={() => setExpanded(!expanded)}>{expanded ? <X size={18}/> : <Maximize2 size={18}/>}</button></div></div>
    <div className="map-toolbar"><div className="map-segments"><button className={!atlas ? 'active' : ''} onClick={() => setAtlas(false)}>This space</button><button className={atlas ? 'active' : ''} onClick={() => setAtlas(true)}>Knowledge atlas</button></div><label className="map-search"><Search size={15}/><input placeholder="Find a concept…" aria-label="Find a concept" value={query} onChange={e => setQuery(e.target.value)}/>{query && <button aria-label="Clear concept search" onClick={() => setQuery('')}><X size={13}/></button>}</label><span className="map-count">{model.nodes.length} concepts · {model.edges.length} connections</span><button className="map-icon-button" aria-label="Export Obsidian canvas" title="Export Obsidian canvas" disabled={!nodes.length} onClick={download}><Download size={17}/></button></div>
    {error && <p className="form-error" role="alert">{error}</p>}
    {!model.nodes.length ? <div className="map-empty"><div className="map-empty-icon"><Network size={40}/></div><h3>Give your ideas a place to meet.</h3><p>Build a learning kit from your conversation, or start with a few concepts and connect them yourself.</p><button className="button secondary" onClick={onEdit}><Pencil size={15}/>Create your first concepts</button></div> : <div className={'map-workbench ' + (node || edge ? 'with-inspector' : '')}>
      <div className="map-surface"><ReactFlow nodes={displayNodes} edges={displayEdges} nodeTypes={nodeTypes} onNodesChange={onNodesChange} onInit={setInstance} onNodeClick={(_, n) => { setSelected(n.id); setSelectedEdge(null); }} onEdgeClick={(_, e) => { setSelectedEdge(e.id); setSelected(null); }} onPaneClick={() => { setSelected(null); setSelectedEdge(null); }} onNodeDragStop={(_, n) => { if (!atlas) run(() => onLayout(n.data.topicId, { [n.data.id]: n.position })); }} nodesDraggable={!atlas} nodesConnectable={false} deleteKeyCode={null} fitView minZoom={.1} maxZoom={1.8} attributionPosition="bottom-right"><Background color="#d7dfd3" gap={24} size={1}/><Controls showInteractive={false}/><MiniMap pannable zoomable nodeColor="#dce7d6" maskColor="#f4f6efb3"/></ReactFlow>
        {query && <div className="map-search-results"><strong>{matches.length} matches</strong>{matches.slice(0, 12).map(n => <button key={n.id} onClick={() => selectNode(n.id)}>{n.data.label}<small>{n.data.topicTitle}</small></button>)}{matches.length === 0 && <p>Try another name or description.</p>}</div>}
        <div className="map-canvas-tools"><button onClick={() => { const next = layoutGraph(model.nodes, model.edges, false); setNodes(next); instance?.fitView({ duration: 350 }); if (!atlas) run(() => onLayout(topic.id, Object.fromEntries(next.map(n => [n.data.id, n.position])))); }} disabled={saving}><Sparkles size={14}/>Arrange</button><button disabled={!selected} className={focus ? 'active' : ''} onClick={() => { setFocus(!focus); setTimeout(() => instance?.fitView({ duration: 350 }), 80); }}><LocateFixed size={14}/>{focus ? 'Show all' : 'Nearby'}</button><span>{saving ? 'Saving…' : atlas ? 'Explore across spaces' : 'Drag to arrange · Saved automatically'}</span></div>
      </div>
      {(node || edge) && <aside className="map-inspector" aria-label="Concept details"><button className="inspector-close" aria-label="Close concept details" onClick={() => { setSelected(null); setSelectedEdge(null); }}><X size={17}/></button>{node ? <><div className="eyebrow">{node.data.topicTitle}</div><h3>{node.data.label}</h3><p className="concept-description">{node.data.description || 'This concept does not have a description yet.'}</p><button className="button secondary" onClick={() => onAsk(node.data.label, node.data.topicId)}><Sparkles size={14}/>Explore with Lumen</button>
        <div className="inspector-section"><h4>Connections <span>{connectedEdges.length}</span></h4>{connectedEdges.length ? connectedEdges.map(e => { const other = model.nodes.find(n => n.id === (e.source === node.id ? e.target : e.source)); return <button className="relationship-row" key={e.id} onClick={() => selectNode(other.id)}><span>{e.source === node.id ? '→' : '←'} {e.label}</span><strong>{other.data.label}</strong>{e.data.source && <small>{e.data.source}</small>}</button>; }) : <p className="inspector-hint">No connections in this view yet.</p>}</div>
        <div className="inspector-section"><h4>Recall this concept <span>{node.data.cards.length}</span></h4>{node.data.cards.map(c => <div className="concept-card-row" key={c.id}><button className="concept-card-link" onClick={() => onCards(node.data.topicId)}><Layers size={14}/><span>{c.front}<small>{c.reviews} reviews · {dueLabel(c)}</small></span></button><button className="unlink-card" aria-label="Unlink flashcard" title="Unlink from this concept; keep the flashcard" disabled={saving} onClick={() => run(() => onAttachCard(node.data.topicId, node.data.id, c.id, true))}><X size={13}/></button></div>)}<label className="inspector-label">Link a flashcard<select aria-label="Link a flashcard" value="" onChange={e => e.target.value && run(() => onAttachCard(node.data.topicId, node.data.id, e.target.value))}><option value="">Choose a card…</option>{topics.find(t => t.id === node.data.topicId)?.cards.filter(c => !c.suspended && !node.data.cardIds?.includes(c.id)).map(c => <option key={c.id} value={c.id}>{c.front.slice(0, 90)}</option>)}</select></label><p className="inspector-hint">Linked cards show practice, not clinical mastery.</p></div>
        {!!allOtherConcepts.length && <div className="inspector-section"><h4>Connect another space</h4><label className="inspector-label">Concept<select aria-label="Concept in another space" value={target} onChange={e => setTarget(e.target.value)}><option value="">Choose a concept…</option>{allOtherConcepts.map(n => <option key={n.value} value={n.value}>{n.topic.title} / {n.label}</option>)}</select></label><label className="inspector-label">Relationship<input aria-label="Cross-space relationship" value={relationship} onChange={e => setRelationship(e.target.value)} maxLength={120}/></label><label className="inspector-label">Source title or URL<input aria-label="Cross-space source" placeholder="Where is this connection explained?" value={relationshipSource} maxLength={2000} onChange={e => setRelationshipSource(e.target.value)}/></label><button className="button secondary" disabled={!target || !relationship.trim() || saving} onClick={() => run(async () => { const other = allOtherConcepts.find(n => n.value === target); await onLink({ fromTopic: node.data.topicId, fromNode: node.data.id, toTopic: other.topic.id, toNode: other.id, label: relationship.trim(), source: relationshipSource.trim() }); setAtlas(true); setTarget(''); setRelationshipSource(''); })}><Link2 size={14}/>Connect concepts</button></div>}
        {node.data.topicId !== topic.id && <button className="text-button" onClick={() => onOpenTopic(node.data.topicId)}>Open learning space<ArrowUpRight size={14}/></button>}
      </> : <><div className="eyebrow">{edge.data.crossTopic ? 'BETWEEN LEARNING SPACES' : 'CONNECTION'}</div><h3>{edge.label}</h3><p>{model.nodes.find(n => n.id === edge.source)?.data.label} → {model.nodes.find(n => n.id === edge.target)?.data.label}</p><h4>Source</h4>{safeURL(edge.data.source) ? <a href={edge.data.source} target="_blank" rel="noreferrer">Read source<ArrowUpRight size={14}/></a> : <p>{edge.data.source || 'No source attached. Check this relationship against your material.'}</p>}{edge.data.crossTopic && <CrossLinkEditor key={`${edge.id}:${edge.label}:${edge.data.source || ''}`} edge={edge} busy={saving} save={fields => run(() => onUpdateLink(edge.id, fields))}/>} {edge.data.crossTopic && <button className="text-button danger" onClick={() => run(async () => { await onUnlink(edge.id); setSelectedEdge(null); })}>Remove connection</button>}</>}</aside>}
    </div>}
    <div className="map-footer"><span><i/>Concept</span><span><i className="connection-key"/>Relationship</span><span><i className="cross-key"/>Across spaces</span><p>Understanding grows through connections.</p></div>
  </section>;
}
