import React from 'react';
import { ArrowUpRight, BookOpen, Check, Flame, Layers, Network, Sprout } from 'lucide-react';
import { isDue } from './study.js';
const dayKey = value => new Date(value).toLocaleDateString('sv-SE');
export function LearningOverview({ db, openTopic, review }) {
  if (!db.topics.length) return null;
  const cards = db.topics.flatMap(t => t.cards.filter(c => !c.suspended));
  const due = cards.filter(c => isDue(c)).length;
  const today = db.reviews.filter(r => dayKey(r.at) === dayKey(Date.now())).length;
  return <section className="learning-overview" aria-label="Your learning overview"><div className="overview-heading"><h2>Pick up where you left off</h2><span>{today ? `${today} reviews today` : 'A little practice goes a long way'}</span></div><div className="overview-metrics"><span><Layers size={15}/><strong>{due}</strong>ready to recall</span><span><Network size={15}/><strong>{db.topics.reduce((n, t) => n + t.graph.nodes.length, 0)}</strong>connected concepts</span><span><Sprout size={15}/><strong>{db.reviews.length}</strong>recall attempts</span></div><div className="space-cards">{db.topics.slice(0, 6).map(t => { const active = t.cards.filter(c => !c.suspended), due = active.filter(c => isDue(c)).length, practised = active.filter(c => c.reviews > 0).length; return <article className="space-card" key={t.id}><div className="space-card-top"><BookOpen size={18}/><span>{t.anki?.enabled ? 'ANKI CONNECTED' : 'LEARNING SPACE'}</span></div><button className="space-title" onClick={() => openTopic(t.id)}>{t.title}<ArrowUpRight size={16}/></button><p>{t.sources.length} sources · {t.graph.nodes.length} concepts · {active.length} cards</p><div className="space-recall-progress" aria-label={`${practised} of ${active.length} cards practised`}><span style={{ width: `${active.length ? 100 * practised / active.length : 0}%` }}/></div><div className="space-card-bottom"><span>{practised ? `${practised} cards practised` : 'Ready for your curiosity'}</span>{due > 0 && <button onClick={() => review(t.id)}>Review {due}<ArrowUpRight size={13}/></button>}</div></article>; })}</div></section>;
}
export function Activity({ reviews, topics }) {
  const counts = new Map(); for (const r of reviews) counts.set(dayKey(r.at), (counts.get(dayKey(r.at)) || 0) + 1);
  const days = Array.from({ length: 28 }, (_, i) => { const d = new Date(); d.setHours(12, 0, 0, 0); d.setDate(d.getDate() - 27 + i); return { key: dayKey(d), label: d.toLocaleDateString(undefined, { weekday: 'short', day: 'numeric', month: 'short' }) }; });
  const recent = [...reviews].sort((a, b) => new Date(b.at) - new Date(a.at)).slice(0, 8);
  return <div className="activity-layout"><section className="activity-calendar"><div className="activity-title"><div><h3>The rhythm of learning</h3><p>Your last four weeks of retrieval practice</p></div><Flame size={22}/></div><div className="activity-days">{days.map(d => { const count = counts.get(d.key) || 0; return <div key={d.key} tabIndex={0} title={`${d.label}: ${count} reviews`} aria-label={`${d.label}: ${count} reviews`} className={`activity-day level-${Math.min(3, Math.ceil(count / 5))}`}><span>{Number(d.key.slice(-2))}</span><small>{count || '·'}</small></div>; })}</div><div className="activity-legend"><span>Less</span>{[0, 1, 2, 3].map(n => <i className={`level-${n}`} key={n}/>)}<span>More</span></div></section><section className="recent-reviews"><h3>Recent recall</h3>{!recent.length && <p>Your first review is the beginning of a useful habit.</p>}{recent.map(r => { const t = topics.find(t => t.id === r.topicId), c = t?.cards.find(c => c.id === r.cardId); return <div className="recent-review" key={r.id}><span className={`grade-dot ${r.grade}`}/><div><strong>{c?.front || 'Archived flashcard'}</strong><small>{t?.title || 'Archived space'} · {r.scheduler === 'anki' ? 'Anki' : 'Lumen'} · {new Date(r.at).toLocaleDateString()}</small></div><span>{r.grade}</span></div>; })}</section></div>;
}
